export const images = {
    splash : require('../images/mental-health.png'),
    home: require('../images/home.png'),
    settings: require('../images/settings.png'),
    progress: require('../images/bar-chart.png'),
    hobbies: require('../images/calendar.png'),
    add: require('../images/add.png'),
    appleLogo : require('../images/apple-logo.png'),
    googleLogo : require('../images/google.png'),
    back: require('../images/left.png'),
    right: require('../images/right.png'),
    notifications: require('../images/bell.png'),
    about: require('../images/exclamation-mark-in-a-circle.png'),
    language: require('../images/internet.png'),
    darkmode: require('../images/light-bulb.png'),
    security: require('../images/lock.png'),
    support: require('../images/old-typical-phone.png'),
    rate: require('../images/star.png'),
    personal: require('../images/user.png'),
    logout: require('../images/logout.png'),
    close : require('../images/close.png'),
    search : require('../images/search.png'),
    sports : require('../images/biceps.png'),
    social : require('../images/group.png'),
    learning : require('../images/stack-of-books.png'),
    finance : require('../images/money.png'),
    healthy : require('../images/plant.png'),
    sleep : require('../images/zzz.png'),
    down: require('../images/down-arrow.png'),
    plus: require('../images/plus.png'),
    minus: require('../images/minus.png'),
    user: require('../images/user.png'),
    edit: require('../images/pencil.png'),
}