export const colors = {
    white:'white',
    black:'black',
    gray: 'gray',
    lightgray: 'lightgray',
    darkgray: 'darkgray',
    red: 'red',
    green: 'green',
    yellow: '#FEBE10',
    desc: '#708090',
    borderClr : '#ccc',
    purple: 'purple',
    searchbar : '#e4e4e4',
    orange: '#FFA07A',
    redTitle : '#AA0000',
    transparent: 'transparent',
    trackcolor_false : '#767577',
    trackcolor_true : '#81b0ff',
    thumbcolor_false : '#f5dd4b',
    thumbcolor_true : '#f4f3f4',
    ios_bg : '#3e3e3e',
    settingsBgc : '#1B1212',
    blue: 'blue',
    background: '#FDFCF6',
    text: '#212529',
    btnBackground : '#212529',
    tabIcon : '#D0B5F3',
    cat1 : '#D6E6F6',
    cat2: '#FCE9D2',
    cat3: '#F9E5E3',
    cat4: '#DAF3EF',
    cat5: '#FBF6DC',
    cat6: '#FCE9F9',
    pink: '#FCE9F9',
}